package mcpserver

const p1CursorSchema = `{"type":"string","pattern":"^(sf1|sl1|bm1|tx1|dt1|dm1)\\.[A-Za-z0-9_-]{2,24}\\.[A-Za-z0-9_-]{43}$"}`
const indexListInputSchema = `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"properties":{"instanceId":` + instanceIDSchema + `,"limit":{"type":"integer","minimum":1,"maximum":100,"default":20},"cursor":` + p1CursorSchema + `}}`
const sourceLinesInputSchema = `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"required":["start","end"],"properties":{"instanceId":` + instanceIDSchema + `,"start":` + addressSchema + `,"end":` + addressSchema + `,"limit":{"type":"integer","minimum":1,"maximum":100,"default":20},"cursor":` + p1CursorSchema + `}}`
const nameDemangleInputSchema = `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"properties":{"instanceId":` + instanceIDSchema + `,"address":` + addressSchema + `,"name":{"type":"string","minLength":1,"maxLength":4096}},"oneOf":[{"required":["address"],"not":{"required":["name"]}},{"required":["name"],"not":{"required":["address"]}}]}`
const commentGetInputSchema = `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"required":["address"],"properties":{"instanceId":` + instanceIDSchema + `,"address":` + addressSchema + `,"scope":{"type":"string","enum":["item","function"],"default":"item"},"repeatable":{"type":"boolean","default":false}}}`
const typeXrefsInputSchema = `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"required":["name"],"properties":{"instanceId":` + instanceIDSchema + `,"name":{"type":"string","minLength":1,"maxLength":4096},"limit":{"type":"integer","minimum":1,"maximum":100,"default":20},"cursor":` + p1CursorSchema + `}}`
const decompilerLocalsInputSchema = `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"required":["address"],"properties":{"instanceId":` + instanceIDSchema + `,"address":` + addressSchema + `,"maxItems":{"type":"integer","minimum":1,"maximum":512,"default":100}}}`
const decompilerCtreeInputSchema = `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"required":["address"],"properties":{"instanceId":` + instanceIDSchema + `,"address":` + addressSchema + `,"maxDepth":{"type":"integer","minimum":1,"maximum":32,"default":8},"maxNodes":{"type":"integer","minimum":1,"maximum":1000,"default":200}}}`
const decompilerLocalXrefsInputSchema = `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"required":["address","localIndex"],"properties":{"instanceId":` + instanceIDSchema + `,"address":` + addressSchema + `,"localIndex":{"type":"integer","minimum":0,"maximum":1000000},"maxDepth":{"type":"integer","minimum":1,"maximum":32,"default":16},"maxNodes":{"type":"integer","minimum":1,"maximum":5000,"default":1000},"maxItems":{"type":"integer","minimum":1,"maximum":512,"default":100}}}`
