package mcpserver

const readonlyAddressInputSchema = `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"required":["address"],"properties":{"instanceId":` + instanceIDSchema + `,"address":` + addressSchema + `}}`
const readonlyPageInputSchema = `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"required":["address"],"properties":{"instanceId":` + instanceIDSchema + `,"address":` + addressSchema + `,"offset":{"type":"integer","minimum":0,"maximum":1000000,"default":0},"limit":{"type":"integer","minimum":1,"maximum":100,"default":20}}}`
const tryBlocksInputSchema = `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"required":["address"],"properties":{"instanceId":` + instanceIDSchema + `,"address":` + addressSchema + `,"limit":{"type":"integer","minimum":1,"maximum":100,"default":20}}}`
const addressListInputSchema = `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"dependentRequired":{"start":["end"],"end":["start"]},"properties":{"instanceId":` + instanceIDSchema + `,"start":` + addressSchema + `,"end":` + addressSchema + `,"limit":{"type":"integer","minimum":1,"maximum":100,"default":20},"cursor":{"type":"string","pattern":"^fx1\\.[A-Za-z0-9_-]{4,24}\\.[A-Za-z0-9_-]{43}$"}}}`
const analysisStatusInputSchema = `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"properties":{"instanceId":` + instanceIDSchema + `}}`
const analysisWaitInputSchema = `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"properties":{"instanceId":` + instanceIDSchema + `,"timeoutMs":{"type":"integer","minimum":100,"maximum":60000,"default":10000},"pollIntervalMs":{"type":"integer","minimum":50,"maximum":2000,"default":200}}}`
const analysisPlanInputSchema = `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"required":["start","end","confirm"],"properties":{"instanceId":` + instanceIDSchema + `,"start":` + addressSchema + `,"end":` + addressSchema + `,"confirm":{"const":true}}}`
const problemTypeSchema = `{"type":"string","enum":["no_base","no_name","no_forced_operand","no_comment","no_xrefs","jump_table","disassembly","head","illegal_address","many_lines","bad_stack","attention","final_decision","rolled_back","flair_collision","flair_indecision"]}`
const analysisProblemsInputSchema = `{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","additionalProperties":false,"required":["type"],"properties":{"instanceId":` + instanceIDSchema + `,"type":` + problemTypeSchema + `,"start":` + addressSchema + `,"limit":{"type":"integer","minimum":1,"maximum":100,"default":20},"cursor":{"type":"string","pattern":"^pr1\\.[A-Za-z0-9_-]{4,24}\\.[A-Za-z0-9_-]{43}$"}}}`
