# Private, reproducible static dependencies; OpenSSL stays a system shared library.
enable_language(C)
include(FetchContent)
set(OPENSSL_USE_STATIC_LIBS FALSE)
find_package(OpenSSL 3 REQUIRED)
foreach(_library IN ITEMS OPENSSL_SSL_LIBRARY OPENSSL_CRYPTO_LIBRARY)
    if(NOT "${${_library}}" MATCHES "\\.so(\\.[0-9.]+)?$")
        message(FATAL_ERROR "The Linux AI backend requires shared system OpenSSL 3 libraries (libssl-dev).")
    endif()
endforeach()

function(ida_agent_build_curl)
    set(BUILD_SHARED_LIBS OFF)
    set(BUILD_STATIC_LIBS ON)
    set(BUILD_CURL_EXE OFF)
    set(BUILD_TESTING OFF)
    set(BUILD_EXAMPLES OFF)
    set(BUILD_LIBCURL_DOCS OFF)
    set(BUILD_MISC_DOCS OFF)
    set(ENABLE_CURL_MANUAL OFF)
    set(CURL_DISABLE_INSTALL ON)
    set(CURL_ENABLE_EXPORT_TARGET OFF)
    set(CMAKE_POSITION_INDEPENDENT_CODE ON)
    set(CMAKE_C_VISIBILITY_PRESET hidden)
    set(ENABLE_THREADED_RESOLVER ON)
    set(ENABLE_ARES OFF)
    set(ENABLE_IPV6 ON)
    set(ENABLE_UNIX_SOCKETS OFF)
    set(CURL_ENABLE_SSL ON)
    set(CURL_USE_OPENSSL ON)
    foreach(_feature MBEDTLS WOLFSSL GNUTLS RUSTLS LIBSSH LIBSSH2 GSASL GSSAPI LIBPSL LIBUV)
        set(CURL_USE_${_feature} OFF)
    endforeach()
    foreach(_feature NGHTTP2 NGTCP2 QUICHE LIBIDN2 HTTPSRR ECH)
        set(USE_${_feature} OFF)
    endforeach()
    foreach(_feature ZLIB BROTLI ZSTD)
        set(CURL_${_feature} OFF CACHE STRING "Unused compression dependency" FORCE)
    endforeach()
    # HTTP_ONLY also disables WebSocket, so explicitly disable unused protocols.
    set(HTTP_ONLY OFF)
    foreach(_feature DICT FILE FTP GOPHER IMAP LDAP LDAPS MQTT POP3 RTSP SMTP TELNET TFTP
            ALTSVC COOKIES AWS DOH HSTS HTTPSIG IPFS KERBEROS_AUTH NEGOTIATE_AUTH
            MIME FORM_API NETRC PARSEDATE PROGRESS_METER BINDLOCAL SHUFFLE_DNS)
        set(CURL_DISABLE_${_feature} ON)
    endforeach()
    foreach(_feature HTTP WEBSOCKETS PROXY HTTP_AUTH BASIC_AUTH BEARER_AUTH DIGEST_AUTH)
        set(CURL_DISABLE_${_feature} OFF)
    endforeach()
    set(CURL_ENABLE_NTLM ON)
    set(CURL_ENABLE_SMB OFF)
    FetchContent_Declare(ida_curl
        URL https://curl.se/download/curl-8.22.0.tar.xz
        URL_HASH SHA256=f7ef3ae8a22e521f289803fe93543eb64c329b58aa73a9e224dfd915a2a5f4f7
        TLS_VERIFY TRUE
        DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
    FetchContent_MakeAvailable(ida_curl)
    target_compile_definitions(libcurl_static PRIVATE CURL_STATICLIB)
    # The final shared consumer must not export third-party APIs or bind to IDA's copies.
    target_link_options(libcurl_static INTERFACE "LINKER:--exclude-libs,libcurl.a")
endfunction()
ida_agent_build_curl()

include("${CMAKE_CURRENT_LIST_DIR}/SqliteDependency.cmake")
