#pragma once

#include "ai/agent_tool_registry.hpp"

#include <cstdint>
#include <functional>
#include <optional>
#include <string>
#include <string_view>
#include <thread>
#include <vector>

namespace ida_agent::ai
{

enum class AgentEffectName
{
  ChangeSetApply,
  ChangeSetRollback,
  DatabaseSave,
  AnalysisPlan,
  DebuggerSelect,
  DebuggerConfigure,
  DebuggerAttach,
  DebuggerDetach,
  DebuggerSuspend,
  DebuggerStart,
  DebuggerExit,
  DebuggerControl,
  DebuggerBreakpoint,
  DebuggerMemoryWrite,
  FileMutate,
  ScriptExecuteFile,
};

enum class AgentEffectRisk
{
  Medium,
  High,
  Critical,
};

enum class AgentEffectStatus
{
  Prepared,
  Confirmed,
  Rejected,
  UnsupportedTool,
  PreparationFailed,
  NoPendingPlan,
  PreparedIdMismatch,
  BindingMismatch,
  ExecutionFailed,
  StateUncertain,
};

// The payload is coordinator-owned state and is never suitable for display.
// The summary is generated by the typed service and is the only preparation
// text intended for the Ask-policy decision UI.
struct AgentEffectPreparation
{
  std::string opaque_payload;
  std::string safe_summary;
};

const std::vector<AgentToolDefinition> &AgentEffectToolDefinitions();

class AgentEffectBinding final
{
public:
  AgentEffectBinding(
      std::uint64_t generation,
      std::string database_context,
      std::string database_key);

  std::uint64_t generation() const noexcept;
  const std::string &database_context() const noexcept;
  const std::string &database_key() const noexcept;

  friend bool operator==(
      const AgentEffectBinding &left,
      const AgentEffectBinding &right) noexcept;
  friend bool operator!=(
      const AgentEffectBinding &left,
      const AgentEffectBinding &right) noexcept;

private:
  std::uint64_t generation_;
  std::string database_context_;
  std::string database_key_;
};

class AgentEffectPreparedPlan final
{
public:
  const std::string &prepared_id() const noexcept;
  AgentEffectName effect() const noexcept;
  AgentEffectRisk risk() const noexcept;
  const AgentEffectBinding &binding() const noexcept;
  const std::string &safe_summary() const noexcept;
  const AgentToolCall &call() const noexcept;
  const std::string &payload() const noexcept;

private:
  friend class AgentEffectCoordinator;

  AgentEffectPreparedPlan(
      std::string prepared_id,
      AgentEffectName effect,
      AgentEffectRisk risk,
      AgentEffectBinding binding,
      std::string safe_summary,
      AgentToolCall call,
      std::string payload);

  std::string prepared_id_;
  AgentEffectName effect_;
  AgentEffectRisk risk_;
  AgentEffectBinding binding_;
  std::string safe_summary_;
  AgentToolCall call_;
  std::string payload_;
};

class AgentEffectPrepareResult final
{
public:
  AgentEffectStatus status() const noexcept;
  const std::string &safe_message() const noexcept;
  const std::optional<AgentEffectPreparedPlan> &plan() const noexcept;

private:
  friend class AgentEffectCoordinator;

  AgentEffectPrepareResult(
      AgentEffectStatus status,
      std::string safe_message,
      std::optional<AgentEffectPreparedPlan> plan);

  AgentEffectStatus status_;
  std::string safe_message_;
  std::optional<AgentEffectPreparedPlan> plan_;
};

class AgentEffectDecisionResult final
{
public:
  AgentEffectStatus status() const noexcept;
  const AgentToolResult &tool_result() const noexcept;

private:
  friend class AgentEffectCoordinator;

  AgentEffectDecisionResult(
      AgentEffectStatus status,
      AgentToolResult tool_result);

  AgentEffectStatus status_;
  AgentToolResult tool_result_;
};

// Controller-owned, main-thread-only coordinator. Every public operation must
// be used on the thread that constructed the instance.
class AgentEffectCoordinator final
{
public:
  using PrepareInvoker = std::function<AgentEffectPreparation(
      AgentEffectName, const AgentToolCall &)>;
  using ExecuteInvoker = std::function<AgentToolResult(
      AgentEffectName, const AgentToolCall &, const std::string &)>;

  AgentEffectCoordinator(
      AgentEffectBinding binding,
      PrepareInvoker prepare_invoker,
      ExecuteInvoker execute_invoker);

  AgentEffectCoordinator(const AgentEffectCoordinator &) = delete;
  AgentEffectCoordinator &operator=(const AgentEffectCoordinator &) = delete;
  AgentEffectCoordinator(AgentEffectCoordinator &&) = delete;
  AgentEffectCoordinator &operator=(AgentEffectCoordinator &&) = delete;

  AgentEffectPrepareResult Prepare(const AgentToolCall &call);
  AgentEffectDecisionResult Confirm(
      std::string_view prepared_id,
      const AgentEffectBinding &binding);
  AgentEffectDecisionResult Reject(
      std::string_view prepared_id,
      const AgentEffectBinding &binding);
  void Invalidate();

  // Replacing any generation/database identity consumes all pending plans.
  void UpdateBinding(AgentEffectBinding binding);
  std::vector<AgentEffectPreparedPlan> PendingPlans();

private:
  void RequireOwnerThread() const;
  std::string NextPreparedId();

  AgentEffectBinding binding_;
  PrepareInvoker prepare_invoker_;
  ExecuteInvoker execute_invoker_;
  std::thread::id owner_thread_;
  std::uint64_t next_prepared_id_ = 1;
  std::vector<AgentEffectPreparedPlan> pending_;
};

} // namespace ida_agent::ai
